name: Build
on:
  push:
    tags: ["v*"]
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest
      
      - name: Build executable
        run: nicegui-pack --onefile --windowed --name "TextCoder" src/main.py
        env:
          PYTHONPATH: src

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/TextCoder.exe
